version: '3.4'

services:
  php:
    build:
      context: ./api
    image: api_platform_php:latest
    depends_on:
      - db
    volumes:
      - ./api:/srv/api:rw,cached
      - ./api/docker/php/conf.d/api-platform.dev.ini/:/usr/local/etc/php/conf.d/api-platform.ini

  api:
    image: api_platform_nginx:latest
    depends_on:
      - php
    volumes:
      - ./api/public:/srv/api/public:rw
    ports:
      - 8080:80

  db:
    image: mysql:5.7.29
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=api
      - MYSQL_USER=api-platform
      - MYSQL_PASSWORD=!ChangeMe!
    volumes:
      - db-data-mysql:/var/lib/mysql
    ports:
      - 3306:3306

#  admin:
#    build:
#      context: ./admin
#      target: api_platform_admin_development
#      cache_from:
#        - ${ADMIN_IMAGE:-quay.io/api-platform/admin}
#    image: ${ADMIN_IMAGE:-quay.io/api-platform/admin}
#    depends_on:
#      - dev-tls
#    volumes:
#      - ./admin:/usr/src/admin:rw,cached
#      - dev-certs:/usr/src/admin/node_modules/webpack-dev-server/ssl:rw
#    ports:
#      - target: 3000
#        published: 444
#        protocol: tcp

#  dev-tls:
#    build:
#      context: ./docker/dev-tls
#    volumes:
#      - dev-certs:/certs:rw
#    ports:
#      - target: 80
#        published: 80
#        protocol: tcp

volumes:
  db-data: {}
  dev-certs: {}
  db-data-mysql: {}
